export declare const PNG_SIGNATURE_BYTES: Uint8Array;
export declare const GIF87_SIGNATURE_BYTES: Uint8Array;
export declare const GIF89_SIGNATURE_BYTES: Uint8Array;
export declare const WEBP_CHECK_BYTES: Uint8Array;
export declare const checkNativeFeatures: (callback?: ((value: any) => any) | undefined) => Promise<any>;
export declare const ifNeeded: (ignoreNativeAPNG?: boolean) => Promise<void>;
export declare function pngCheck(buffer: ArrayBufferLike): boolean;
export declare function gifCheck(buffer: ArrayBufferLike): boolean;
export declare function webpCheck(buffer: ArrayBufferLike): boolean;
export declare const support: {
    checkNativeFeatures: (callback?: ((value: any) => any) | undefined) => Promise<any>;
    ifNeeded: (ignoreNativeAPNG?: boolean) => Promise<void>;
    pngCheck: typeof pngCheck;
    gifCheck: typeof gifCheck;
    webpCheck: typeof webpCheck;
    PNG_SIGNATURE_BYTES: Uint8Array;
    GIF87_SIGNATURE_BYTES: Uint8Array;
    GIF89_SIGNATURE_BYTES: Uint8Array;
    WEBP_CHECK_BYTES: Uint8Array;
};
